services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - 8085:8085
      - 38888:38888
    volumes:
      - data:/opt/RavenDB/Server/RavenData/
    environment:
      - RAVEN_ServerUrl=http://localhost:8085
    labels:
      - traefik.http.routers.ayaz-memster-frontend.rule=Host(`ravendb.okinazuno.me`)
      - traefik.http.routers.ayaz-memster-frontend.tls=true
      - traefik.http.routers.ayaz-memster-frontend.tls.certresolver=letsEncrypt
      - traefik.http.services.ayaz-memster-frontend.loadbalancer.server.port=8085

volumes:
  data:
