services:
  ravendb:
    container_name: ayaz-memster-ravendb
    image: ravendb/ravendb
    ports:
      - 9600:9600
      - 38888:38888
    volumes:
      - data:/opt/RavenDB/Server/RavenData/
    environment:
      - RAVEN_ServerUrl=http://0.0.0.0:9600
      - RAVEN_PublicServerUrl=http://ravendb.okinazuno.me:9600
      - RAVEN_Logs_Mode=Information
    labels:
      - traefik.http.routers.ayaz-memster-ravendb.rule=Host(`ravendb.okinazuno.me`)
      - traefik.http.routers.ayaz-memster-ravendb.tls=true
      - traefik.http.routers.ayaz-memster-ravendb.tls.certresolver=letsEncrypt
      - traefik.http.services.ayaz-memster-ravendb.loadbalancer.server.port=9600

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-network