services:
  ravendb:
    container_name: ayaz-memster-ravendb
    image: ravendb/ravendb
    ports:
      - 9600:8080
      - 38888:38888
    volumes:
      - data:/opt/RavenDB/Server/RavenData/
      # - ./settings.json:/opt/RavenDB/Server/settings.json
      - ./cert.pfx:/opt/RavenDB/Server/cert.pfx

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-network
