services:
  ravendb:
    container_name: ayaz-memster-ravendb
    image: ravendb/ravendb
    ports:
      - 9600:8080
      - 38888:38888
    volumes:
      - data:/opt/RavenDB/Server/RavenData/
    environment:
      # - RAVEN_ServerUrl=http://localhost:9600
      # - RAVEN_ARGS='-BindPort=9600'
      # - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
      # - RAVEN_Logs_Mode=Information
    # labels:
    #   - traefik.http.routers.ayaz-memster-ravendb.rule=Host(`ravendb.okinazuno.me`)
    #   - traefik.http.routers.ayaz-memster-ravendb.tls=true
    #   - traefik.http.routers.ayaz-memster-ravendb.tls.certresolver=letsEncrypt
    #   - traefik.http.services.ayaz-memster-ravendb.loadbalancer.server.port=9600

volumes:
  data:

# networks:
#   default:
#     external: true
#     name: traefik-network