name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy containers to Azure Virtual Machine
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Copy yaml scripts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          target: '/docker/ayaz-memster-infrastructure/'
          overwrite: true
          source: 'docker-compose.yaml,settings.json'
      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            cd /docker/ayaz-memster-infrastructure
            echo '${{ secrets.RAVEN_CERT64 }}' > cert.base64
            base64 --decode ./cert.base64 > cert.pfx
            docker-compose up -d
            docker image prune -a -f